#!/usr/bin/env python
# Franklin Hu and Sunil Pedapudi
# CS 194-10
# Assignment 2
# confusion-matrix

import sys

if __name__ == "__main__":
  if len(sys.argv) < 4:
    print "Usage: confusion-matrix X Z"
    sys.exit(1)

  filename = sys.argv[1]
  X = sys.argv[2]
  Z = sys.argv[3]



