#!/usr/bin/env python
import csv
import sys

class Counter:
  def __init__(self):
    self.counter = {}

  def increment(self, key):
    if key in self.counter:
      self.counter[key] += 1
    else:
      self.counter[key] = 1

  def get_all(self):
    return self.counter

if __name__ == "__main__":
  if len(sys.argv) < 3:
    print "Usage: discrete-histogram <data-file> <attribute>"
    sys.exit(1)
  filename = sys.argv[1]
  attribute = sys.argv[2]
  attribute_index = -1

  handle = open(filename, 'r')
  header = handle.next()
  header = header.rstrip("\n").split(",")

  for i in xrange(len(header)):
    col = header[i]
    if col == attribute:
      attribute_index = i
      break
  
  if attribute_index == -1:
    print "Invalid attribute"
    sys.exit(2)

  attribute_counter = Counter()
  data = csv.reader(handle)
  for line in data:
    if len(line) > 0:
      value = line[attribute_index]
      attribute_counter.increment(value)

  frequencies = attribute_counter.get_all()
  total = sum(frequencies.values())

  keys = frequencies.keys()
  keys.sort()
  for key in keys:
    print "%s,%s,%s" % (key,frequencies[key],float(frequencies[key])/total)
